### ISSUE TITLE
Version 0.4 diagnostics error

### ISSUE THREAD

**Issue by bradlc** [tailwindcss/intellisense#133]
Version 0.4 now causes:
```bash
(node:87811) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'classNames' of undefined
    at Object.t.getClassNameParts (/Users/xxx/.vscode/extensions/bradlc.vscode-tailwindcss-0.4.0/dist/server/index.js:31:35152)
    at Object.t.getClassNameDecls (/Users/xxx/.vscode/extensions/bradlc.vscode-tailwindcss-0.4.0/dist/server/index.js:45:620)
    at /Users/xxx/.vscode/extensions/bradlc.vscode-tailwindcss-0.4.0/dist/server/index.js:13:71022
    at Array.forEach (<anonymous>)
    at /Users/xxx/.vscode/extensions/bradlc.vscode-tailwindcss-0.4.0/dist/server/index.js:13:70998
    at Array.forEach (<anonymous>)
    at Object.t.getCssConflictDiagnostics (/Users/xxx/.vscode/extensions/bradlc.vscode-tailwindcss-0.4.0/dist/server/index.js:13:70946)
    at /Users/xxx/.vscode/extensions/bradlc.vscode-tailwindcss-0.4.0/dist/server/index.js:1:163263
    at Generator.next (<anonymous>)
    at s (/Users/xxx/.vscode/extensions/bradlc.vscode-tailwindcss-0.4.0/dist/server/index.js:1:162562)
```

_Originally posted by @mbulfair in https://github.com/tailwindcss/intellisense/issues/130#issuecomment-648370674_

**Comment by bradlc** [comment]
Fixed in `v0.4.1`
